import type { SoundAsset } from './asset-types';

export const kenneySounds: SoundAsset[] = [
  {
    id: 'audio_Preview',
    name: 'Preview',
    type: 'sound',
    path: '/assets/audio/audio_Preview.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-fan-1',
    name: 'Card-Fan-1',
    type: 'sound',
    path: '/assets/audio/audio_card-fan-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-fan-2',
    name: 'Card-Fan-2',
    type: 'sound',
    path: '/assets/audio/audio_card-fan-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-place-1',
    name: 'Card-Place-1',
    type: 'sound',
    path: '/assets/audio/audio_card-place-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-place-2',
    name: 'Card-Place-2',
    type: 'sound',
    path: '/assets/audio/audio_card-place-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-place-3',
    name: 'Card-Place-3',
    type: 'sound',
    path: '/assets/audio/audio_card-place-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-place-4',
    name: 'Card-Place-4',
    type: 'sound',
    path: '/assets/audio/audio_card-place-4.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-shove-1',
    name: 'Card-Shove-1',
    type: 'sound',
    path: '/assets/audio/audio_card-shove-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-shove-2',
    name: 'Card-Shove-2',
    type: 'sound',
    path: '/assets/audio/audio_card-shove-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-shove-3',
    name: 'Card-Shove-3',
    type: 'sound',
    path: '/assets/audio/audio_card-shove-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-shove-4',
    name: 'Card-Shove-4',
    type: 'sound',
    path: '/assets/audio/audio_card-shove-4.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-shuffle',
    name: 'Card-Shuffle',
    type: 'sound',
    path: '/assets/audio/audio_card-shuffle.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-1',
    name: 'Card-Slide-1',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-2',
    name: 'Card-Slide-2',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-3',
    name: 'Card-Slide-3',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-4',
    name: 'Card-Slide-4',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-4.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-5',
    name: 'Card-Slide-5',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-5.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-6',
    name: 'Card-Slide-6',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-6.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-7',
    name: 'Card-Slide-7',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-7.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_card-slide-8',
    name: 'Card-Slide-8',
    type: 'sound',
    path: '/assets/audio/audio_card-slide-8.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_cards-pack-open-1',
    name: 'Cards-Pack-Open-1',
    type: 'sound',
    path: '/assets/audio/audio_cards-pack-open-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_cards-pack-open-2',
    name: 'Cards-Pack-Open-2',
    type: 'sound',
    path: '/assets/audio/audio_cards-pack-open-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_cards-pack-take-out-1',
    name: 'Cards-Pack-Take-Out-1',
    type: 'sound',
    path: '/assets/audio/audio_cards-pack-take-out-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_cards-pack-take-out-2',
    name: 'Cards-Pack-Take-Out-2',
    type: 'sound',
    path: '/assets/audio/audio_cards-pack-take-out-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chip-lay-1',
    name: 'Chip-Lay-1',
    type: 'sound',
    path: '/assets/audio/audio_chip-lay-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chip-lay-2',
    name: 'Chip-Lay-2',
    type: 'sound',
    path: '/assets/audio/audio_chip-lay-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chip-lay-3',
    name: 'Chip-Lay-3',
    type: 'sound',
    path: '/assets/audio/audio_chip-lay-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-collide-1',
    name: 'Chips-Collide-1',
    type: 'sound',
    path: '/assets/audio/audio_chips-collide-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-collide-2',
    name: 'Chips-Collide-2',
    type: 'sound',
    path: '/assets/audio/audio_chips-collide-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-collide-3',
    name: 'Chips-Collide-3',
    type: 'sound',
    path: '/assets/audio/audio_chips-collide-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-collide-4',
    name: 'Chips-Collide-4',
    type: 'sound',
    path: '/assets/audio/audio_chips-collide-4.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-handle-1',
    name: 'Chips-Handle-1',
    type: 'sound',
    path: '/assets/audio/audio_chips-handle-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-handle-2',
    name: 'Chips-Handle-2',
    type: 'sound',
    path: '/assets/audio/audio_chips-handle-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-handle-3',
    name: 'Chips-Handle-3',
    type: 'sound',
    path: '/assets/audio/audio_chips-handle-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-handle-4',
    name: 'Chips-Handle-4',
    type: 'sound',
    path: '/assets/audio/audio_chips-handle-4.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-handle-5',
    name: 'Chips-Handle-5',
    type: 'sound',
    path: '/assets/audio/audio_chips-handle-5.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-handle-6',
    name: 'Chips-Handle-6',
    type: 'sound',
    path: '/assets/audio/audio_chips-handle-6.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-stack-1',
    name: 'Chips-Stack-1',
    type: 'sound',
    path: '/assets/audio/audio_chips-stack-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-stack-2',
    name: 'Chips-Stack-2',
    type: 'sound',
    path: '/assets/audio/audio_chips-stack-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-stack-3',
    name: 'Chips-Stack-3',
    type: 'sound',
    path: '/assets/audio/audio_chips-stack-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-stack-4',
    name: 'Chips-Stack-4',
    type: 'sound',
    path: '/assets/audio/audio_chips-stack-4.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-stack-5',
    name: 'Chips-Stack-5',
    type: 'sound',
    path: '/assets/audio/audio_chips-stack-5.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_chips-stack-6',
    name: 'Chips-Stack-6',
    type: 'sound',
    path: '/assets/audio/audio_chips-stack-6.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-grab-1',
    name: 'Dice-Grab-1',
    type: 'sound',
    path: '/assets/audio/audio_dice-grab-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-grab-2',
    name: 'Dice-Grab-2',
    type: 'sound',
    path: '/assets/audio/audio_dice-grab-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-shake-1',
    name: 'Dice-Shake-1',
    type: 'sound',
    path: '/assets/audio/audio_dice-shake-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-shake-2',
    name: 'Dice-Shake-2',
    type: 'sound',
    path: '/assets/audio/audio_dice-shake-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-shake-3',
    name: 'Dice-Shake-3',
    type: 'sound',
    path: '/assets/audio/audio_dice-shake-3.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-throw-1',
    name: 'Dice-Throw-1',
    type: 'sound',
    path: '/assets/audio/audio_dice-throw-1.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'audio_dice-throw-2',
    name: 'Dice-Throw-2',
    type: 'sound',
    path: '/assets/audio/audio_dice-throw-2.ogg',
    tags: ['sound', 'cc0'],
    license: 'CC0 - Kenney.nl',
  },
];

export const kenneyMusic: SoundAsset[] = [];
