import type { BackgroundAsset } from './asset-types';

export const kenneyBackgrounds: BackgroundAsset[] = [
  {
    id: '1-bit_pack_Preview',
    name: 'Preview',
    description: '1-Bit Pack - Preview',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_Preview.png',
    thumbnail: '/assets/misc/1-bit_pack_Preview.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_Sample_fantasy',
    name: 'Sample Fantasy',
    description: '1-Bit Pack - Sample_fantasy',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_Sample_fantasy.png',
    thumbnail: '/assets/misc/1-bit_pack_Sample_fantasy.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_Sample_interior',
    name: 'Sample Interior',
    description: '1-Bit Pack - Sample_interior',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_Sample_interior.png',
    thumbnail: '/assets/misc/1-bit_pack_Sample_interior.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_Sample_platformer',
    name: 'Sample Platformer',
    description: '1-Bit Pack - Sample_platformer',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_Sample_platformer.png',
    thumbnail: '/assets/misc/1-bit_pack_Sample_platformer.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_Sample_urban',
    name: 'Sample Urban',
    description: '1-Bit Pack - Sample_urban',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_Sample_urban.png',
    thumbnail: '/assets/misc/1-bit_pack_Sample_urban.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_colored-transparent',
    name: 'Colored-Transparent',
    description: '1-Bit Pack - colored-transparent',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_colored-transparent.png',
    thumbnail: '/assets/misc/1-bit_pack_colored-transparent.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_colored-transparent_packed',
    name: 'Colored-Transparent Packed',
    description: '1-Bit Pack - colored-transparent_packed',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_colored-transparent_packed.png',
    thumbnail: '/assets/misc/1-bit_pack_colored-transparent_packed.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_colored',
    name: 'Colored',
    description: '1-Bit Pack - colored',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_colored.png',
    thumbnail: '/assets/misc/1-bit_pack_colored.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_colored_packed',
    name: 'Colored Packed',
    description: '1-Bit Pack - colored_packed',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_colored_packed.png',
    thumbnail: '/assets/misc/1-bit_pack_colored_packed.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_monochrome-transparent',
    name: 'Monochrome-Transparent',
    description: '1-Bit Pack - monochrome-transparent',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_monochrome-transparent.png',
    thumbnail: '/assets/misc/1-bit_pack_monochrome-transparent.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_monochrome-transparent_packed',
    name: 'Monochrome-Transparent Packed',
    description: '1-Bit Pack - monochrome-transparent_packed',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_monochrome-transparent_packed.png',
    thumbnail: '/assets/misc/1-bit_pack_monochrome-transparent_packed.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_monochrome',
    name: 'Monochrome',
    description: '1-Bit Pack - monochrome',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_monochrome.png',
    thumbnail: '/assets/misc/1-bit_pack_monochrome.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_pack_monochrome_packed',
    name: 'Monochrome Packed',
    description: '1-Bit Pack - monochrome_packed',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/1-bit_pack_monochrome_packed.png',
    thumbnail: '/assets/misc/1-bit_pack_monochrome_packed.png',
    tags: ['misc', '1-bit_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_platformer_pack_Preview',
    name: 'Preview',
    description: '1-Bit Platformer Pack - Preview',
    type: 'background',
    category: 'tiles',
    path: '/assets/tiles/1-bit_platformer_pack_Preview.png',
    thumbnail: '/assets/tiles/1-bit_platformer_pack_Preview.png',
    tags: ['tiles', '1-bit_platformer_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: '1-bit_platformer_pack_Sample',
    name: 'Sample',
    description: '1-Bit Platformer Pack - Sample',
    type: 'background',
    category: 'tiles',
    path: '/assets/tiles/1-bit_platformer_pack_Sample.png',
    thumbnail: '/assets/tiles/1-bit_platformer_pack_Sample.png',
    tags: ['tiles', '1-bit_platformer_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_Preview',
    name: 'Preview',
    description: 'Abstract Platformer - Preview',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_Preview.png',
    thumbnail: '/assets/misc/abstract_platformer_Preview.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_Sample',
    name: 'Sample',
    description: 'Abstract Platformer - Sample',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_Sample.png',
    thumbnail: '/assets/misc/abstract_platformer_Sample.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set1_background',
    name: 'Set1 Background',
    description: 'Abstract Platformer - set1_background',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set1_background.png',
    thumbnail: '/assets/misc/abstract_platformer_set1_background.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set1_hills',
    name: 'Set1 Hills',
    description: 'Abstract Platformer - set1_hills',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set1_hills.png',
    thumbnail: '/assets/misc/abstract_platformer_set1_hills.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set2_background',
    name: 'Set2 Background',
    description: 'Abstract Platformer - set2_background',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set2_background.png',
    thumbnail: '/assets/misc/abstract_platformer_set2_background.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set2_hills',
    name: 'Set2 Hills',
    description: 'Abstract Platformer - set2_hills',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set2_hills.png',
    thumbnail: '/assets/misc/abstract_platformer_set2_hills.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set3_background',
    name: 'Set3 Background',
    description: 'Abstract Platformer - set3_background',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set3_background.png',
    thumbnail: '/assets/misc/abstract_platformer_set3_background.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set3_hills',
    name: 'Set3 Hills',
    description: 'Abstract Platformer - set3_hills',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set3_hills.png',
    thumbnail: '/assets/misc/abstract_platformer_set3_hills.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set4_background',
    name: 'Set4 Background',
    description: 'Abstract Platformer - set4_background',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set4_background.png',
    thumbnail: '/assets/misc/abstract_platformer_set4_background.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'abstract_platformer_set4_hills',
    name: 'Set4 Hills',
    description: 'Abstract Platformer - set4_hills',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_set4_hills.png',
    thumbnail: '/assets/misc/abstract_platformer_set4_hills.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'alien_ufo_pack_Preview',
    name: 'Preview',
    description: 'Alien UFO Pack - Preview',
    type: 'background',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_Preview.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_Preview.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'alien_ufo_pack_Sample',
    name: 'Sample',
    description: 'Alien UFO Pack - Sample',
    type: 'background',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_Sample.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_Sample.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'animal_pack_Preview',
    name: 'Preview',
    description: 'Animal Pack - Preview',
    type: 'background',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_Preview.png',
    thumbnail: '/assets/enemies/animal_pack_Preview.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'animal_pack_redux_Preview',
    name: 'Preview',
    description: 'Animal Pack Redux - Preview',
    type: 'background',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_Preview.png',
    thumbnail: '/assets/enemies/animal_pack_redux_Preview.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'axonometric_blocks_Preview',
    name: 'Preview',
    description: 'Axonometric Blocks - Preview',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/axonometric_blocks_Preview.png',
    thumbnail: '/assets/misc/axonometric_blocks_Preview.png',
    tags: ['misc', 'axonometric_blocks'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'axonometric_blocks_Sample_1',
    name: 'Sample 1',
    description: 'Axonometric Blocks - Sample 1',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/axonometric_blocks_Sample_1.png',
    thumbnail: '/assets/misc/axonometric_blocks_Sample_1.png',
    tags: ['misc', 'axonometric_blocks'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'axonometric_blocks_Sample_2',
    name: 'Sample 2',
    description: 'Axonometric Blocks - Sample 2',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/axonometric_blocks_Sample_2.png',
    thumbnail: '/assets/misc/axonometric_blocks_Sample_2.png',
    tags: ['misc', 'axonometric_blocks'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'axonometric_blocks_Sample_3',
    name: 'Sample 3',
    description: 'Axonometric Blocks - Sample 3',
    type: 'background',
    category: 'misc',
    path: '/assets/misc/axonometric_blocks_Sample_3.png',
    thumbnail: '/assets/misc/axonometric_blocks_Sample_3.png',
    tags: ['misc', 'axonometric_blocks'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_Preview',
    name: 'Preview',
    description: 'Background Elements - Preview',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_Preview.png',
    thumbnail: '/assets/backgrounds/background_elements_Preview.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_Sample',
    name: 'Sample',
    description: 'Background Elements - Sample',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_Sample.png',
    thumbnail: '/assets/backgrounds/background_elements_Sample.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_Preview',
    name: 'Preview',
    description: 'Background Elements Redux - Preview',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_Preview.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_Preview.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_Sample',
    name: 'Sample',
    description: 'Background Elements Redux - Sample',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_Sample.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_Sample.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundCastles',
    name: 'Backgroundcastles',
    description: 'Background Elements Redux - backgroundCastles',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundCastles.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundCastles.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundColorDesert',
    name: 'Backgroundcolordesert',
    description: 'Background Elements Redux - backgroundColorDesert',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundColorDesert.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundColorDesert.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundColorFall',
    name: 'Backgroundcolorfall',
    description: 'Background Elements Redux - backgroundColorFall',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundColorFall.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundColorFall.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundColorForest',
    name: 'Backgroundcolorforest',
    description: 'Background Elements Redux - backgroundColorForest',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundColorForest.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundColorForest.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundColorGrass',
    name: 'Backgroundcolorgrass',
    description: 'Background Elements Redux - backgroundColorGrass',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundColorGrass.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundColorGrass.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundDesert',
    name: 'Backgrounddesert',
    description: 'Background Elements Redux - backgroundDesert',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundDesert.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundDesert.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundEmpty',
    name: 'Backgroundempty',
    description: 'Background Elements Redux - backgroundEmpty',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundEmpty.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundEmpty.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_backgroundForest',
    name: 'Backgroundforest',
    description: 'Background Elements Redux - backgroundForest',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_backgroundForest.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_backgroundForest.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_cloudLayer1',
    name: 'Cloudlayer1',
    description: 'Background Elements Redux - cloudLayer1',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_cloudLayer1.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_cloudLayer1.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_cloudLayer2',
    name: 'Cloudlayer2',
    description: 'Background Elements Redux - cloudLayer2',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_cloudLayer2.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_cloudLayer2.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_cloudLayerB1',
    name: 'Cloudlayerb1',
    description: 'Background Elements Redux - cloudLayerB1',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_cloudLayerB1.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_cloudLayerB1.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_cloudLayerB2',
    name: 'Cloudlayerb2',
    description: 'Background Elements Redux - cloudLayerB2',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_cloudLayerB2.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_cloudLayerB2.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
  {
    id: 'background_elements_redux_groundLayer1',
    name: 'Groundlayer1',
    description: 'Background Elements Redux - groundLayer1',
    type: 'background',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_groundLayer1.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_groundLayer1.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
  },
];
