// Auto-generated Kenney asset manifests
import type { SpriteAsset } from './asset-types';

export const kenneySprites: SpriteAsset[] = [
  {
    id: 'abstract_platformer_enemyFloating_1',
    name: 'Enemyfloating 1',
    description: 'Abstract Platformer - enemyFloating_1',
    type: 'sprite',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_enemyFloating_1.png',
    thumbnail: '/assets/misc/abstract_platformer_enemyFloating_1.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Abstract Platformer pack',
    size: { width: 42, height: 40 },
  },
  {
    id: 'abstract_platformer_enemyFloating_2',
    name: 'Enemyfloating 2',
    description: 'Abstract Platformer - enemyFloating_2',
    type: 'sprite',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_enemyFloating_2.png',
    thumbnail: '/assets/misc/abstract_platformer_enemyFloating_2.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Abstract Platformer pack',
    size: { width: 55, height: 55 },
  },
  {
    id: 'abstract_platformer_enemyFloating_3',
    name: 'Enemyfloating 3',
    description: 'Abstract Platformer - enemyFloating_3',
    type: 'sprite',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_enemyFloating_3.png',
    thumbnail: '/assets/misc/abstract_platformer_enemyFloating_3.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Abstract Platformer pack',
    size: { width: 40, height: 40 },
  },
  {
    id: 'abstract_platformer_enemyFloating_4',
    name: 'Enemyfloating 4',
    description: 'Abstract Platformer - enemyFloating_4',
    type: 'sprite',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_enemyFloating_4.png',
    thumbnail: '/assets/misc/abstract_platformer_enemyFloating_4.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Abstract Platformer pack',
    size: { width: 42, height: 40 },
  },
  {
    id: 'abstract_platformer_enemyFlyingAlt_1',
    name: 'Enemyflyingalt 1',
    description: 'Abstract Platformer - enemyFlyingAlt_1',
    type: 'sprite',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_enemyFlyingAlt_1.png',
    thumbnail: '/assets/misc/abstract_platformer_enemyFlyingAlt_1.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Abstract Platformer pack',
    size: { width: 52, height: 36 },
  },
  {
    id: 'abstract_platformer_enemyFlyingAlt_2',
    name: 'Enemyflyingalt 2',
    description: 'Abstract Platformer - enemyFlyingAlt_2',
    type: 'sprite',
    category: 'misc',
    path: '/assets/misc/abstract_platformer_enemyFlyingAlt_2.png',
    thumbnail: '/assets/misc/abstract_platformer_enemyFlyingAlt_2.png',
    tags: ['misc', 'abstract_platformer'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Abstract Platformer pack',
    size: { width: 63, height: 24 },
  },
  {
    id: 'alien_ufo_pack_dome',
    name: 'Dome',
    description: 'Alien UFO Pack - dome',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_dome.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_dome.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 83, height: 98 },
  },
  {
    id: 'alien_ufo_pack_laserBeige1',
    name: 'Laserbeige1',
    description: 'Alien UFO Pack - laserBeige1',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBeige1.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBeige1.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 38, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserBeige2',
    name: 'Laserbeige2',
    description: 'Alien UFO Pack - laserBeige2',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBeige2.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBeige2.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 68, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserBeige3',
    name: 'Laserbeige3',
    description: 'Alien UFO Pack - laserBeige3',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBeige3.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBeige3.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 93, height: 35 },
  },
  {
    id: 'alien_ufo_pack_laserBeige_burst',
    name: 'Laserbeige Burst',
    description: 'Alien UFO Pack - laserBeige_burst',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBeige_burst.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBeige_burst.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 188, height: 188 },
  },
  {
    id: 'alien_ufo_pack_laserBeige_groundBurst',
    name: 'Laserbeige Groundburst',
    description: 'Alien UFO Pack - laserBeige_groundBurst',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBeige_groundBurst.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBeige_groundBurst.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 172, height: 78 },
  },
  {
    id: 'alien_ufo_pack_laserBlue1',
    name: 'Laserblue1',
    description: 'Alien UFO Pack - laserBlue1',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBlue1.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBlue1.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 38, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserBlue2',
    name: 'Laserblue2',
    description: 'Alien UFO Pack - laserBlue2',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBlue2.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBlue2.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 68, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserBlue3',
    name: 'Laserblue3',
    description: 'Alien UFO Pack - laserBlue3',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBlue3.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBlue3.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 93, height: 35 },
  },
  {
    id: 'alien_ufo_pack_laserBlue_burst',
    name: 'Laserblue Burst',
    description: 'Alien UFO Pack - laserBlue_burst',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBlue_burst.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBlue_burst.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 188, height: 188 },
  },
  {
    id: 'alien_ufo_pack_laserBlue_groundBurst',
    name: 'Laserblue Groundburst',
    description: 'Alien UFO Pack - laserBlue_groundBurst',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserBlue_groundBurst.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserBlue_groundBurst.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 172, height: 78 },
  },
  {
    id: 'alien_ufo_pack_laserGreen1',
    name: 'Lasergreen1',
    description: 'Alien UFO Pack - laserGreen1',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserGreen1.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserGreen1.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 38, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserGreen2',
    name: 'Lasergreen2',
    description: 'Alien UFO Pack - laserGreen2',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserGreen2.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserGreen2.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 68, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserGreen3',
    name: 'Lasergreen3',
    description: 'Alien UFO Pack - laserGreen3',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserGreen3.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserGreen3.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 93, height: 35 },
  },
  {
    id: 'alien_ufo_pack_laserGreen_burst',
    name: 'Lasergreen Burst',
    description: 'Alien UFO Pack - laserGreen_burst',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserGreen_burst.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserGreen_burst.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 188, height: 188 },
  },
  {
    id: 'alien_ufo_pack_laserGreen_groundBurst',
    name: 'Lasergreen Groundburst',
    description: 'Alien UFO Pack - laserGreen_groundBurst',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserGreen_groundBurst.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserGreen_groundBurst.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 172, height: 78 },
  },
  {
    id: 'alien_ufo_pack_laserPink1',
    name: 'Laserpink1',
    description: 'Alien UFO Pack - laserPink1',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserPink1.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserPink1.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 38, height: 100 },
  },
  {
    id: 'alien_ufo_pack_laserPink2',
    name: 'Laserpink2',
    description: 'Alien UFO Pack - laserPink2',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/alien_ufo_pack_laserPink2.png',
    thumbnail: '/assets/enemies/alien_ufo_pack_laserPink2.png',
    tags: ['enemies', 'alien_ufo_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Alien UFO Pack pack',
    size: { width: 68, height: 100 },
  },
  {
    id: 'animal_pack_elephant',
    name: 'Elephant',
    description: 'Animal Pack - elephant',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_elephant.png',
    thumbnail: '/assets/enemies/animal_pack_elephant.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 348, height: 282 },
  },
  {
    id: 'animal_pack_giraffe',
    name: 'Giraffe',
    description: 'Animal Pack - giraffe',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_giraffe.png',
    thumbnail: '/assets/enemies/animal_pack_giraffe.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 306, height: 322 },
  },
  {
    id: 'animal_pack_hippo',
    name: 'Hippo',
    description: 'Animal Pack - hippo',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_hippo.png',
    thumbnail: '/assets/enemies/animal_pack_hippo.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 264, height: 264 },
  },
  {
    id: 'animal_pack_monkey',
    name: 'Monkey',
    description: 'Animal Pack - monkey',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_monkey.png',
    thumbnail: '/assets/enemies/animal_pack_monkey.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 308, height: 257 },
  },
  {
    id: 'animal_pack_panda',
    name: 'Panda',
    description: 'Animal Pack - panda',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_panda.png',
    thumbnail: '/assets/enemies/animal_pack_panda.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 304, height: 257 },
  },
  {
    id: 'animal_pack_parrot',
    name: 'Parrot',
    description: 'Animal Pack - parrot',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_parrot.png',
    thumbnail: '/assets/enemies/animal_pack_parrot.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 256, height: 257 },
  },
  {
    id: 'animal_pack_penguin',
    name: 'Penguin',
    description: 'Animal Pack - penguin',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_penguin.png',
    thumbnail: '/assets/enemies/animal_pack_penguin.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 256, height: 257 },
  },
  {
    id: 'animal_pack_pig',
    name: 'Pig',
    description: 'Animal Pack - pig',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_pig.png',
    thumbnail: '/assets/enemies/animal_pack_pig.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 288, height: 257 },
  },
  {
    id: 'animal_pack_rabbit',
    name: 'Rabbit',
    description: 'Animal Pack - rabbit',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_rabbit.png',
    thumbnail: '/assets/enemies/animal_pack_rabbit.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 256, height: 341 },
  },
  {
    id: 'animal_pack_snake',
    name: 'Snake',
    description: 'Animal Pack - snake',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_snake.png',
    thumbnail: '/assets/enemies/animal_pack_snake.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 256, height: 291 },
  },
  {
    id: 'animal_pack_elephant',
    name: 'Elephant',
    description: 'Animal Pack - elephant',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_elephant.png',
    thumbnail: '/assets/enemies/animal_pack_elephant.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 376, height: 310 },
  },
  {
    id: 'animal_pack_giraffe',
    name: 'Giraffe',
    description: 'Animal Pack - giraffe',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_giraffe.png',
    thumbnail: '/assets/enemies/animal_pack_giraffe.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 334, height: 350 },
  },
  {
    id: 'animal_pack_hippo',
    name: 'Hippo',
    description: 'Animal Pack - hippo',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_hippo.png',
    thumbnail: '/assets/enemies/animal_pack_hippo.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 294, height: 293 },
  },
  {
    id: 'animal_pack_monkey',
    name: 'Monkey',
    description: 'Animal Pack - monkey',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_monkey.png',
    thumbnail: '/assets/enemies/animal_pack_monkey.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 336, height: 285 },
  },
  {
    id: 'animal_pack_panda',
    name: 'Panda',
    description: 'Animal Pack - panda',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_panda.png',
    thumbnail: '/assets/enemies/animal_pack_panda.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 332, height: 285 },
  },
  {
    id: 'animal_pack_parrot',
    name: 'Parrot',
    description: 'Animal Pack - parrot',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_parrot.png',
    thumbnail: '/assets/enemies/animal_pack_parrot.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 284, height: 285 },
  },
  {
    id: 'animal_pack_penguin',
    name: 'Penguin',
    description: 'Animal Pack - penguin',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_penguin.png',
    thumbnail: '/assets/enemies/animal_pack_penguin.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 284, height: 285 },
  },
  {
    id: 'animal_pack_pig',
    name: 'Pig',
    description: 'Animal Pack - pig',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_pig.png',
    thumbnail: '/assets/enemies/animal_pack_pig.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 316, height: 285 },
  },
  {
    id: 'animal_pack_rabbit',
    name: 'Rabbit',
    description: 'Animal Pack - rabbit',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_rabbit.png',
    thumbnail: '/assets/enemies/animal_pack_rabbit.png',
    tags: ['enemies', 'animal_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack pack',
    size: { width: 284, height: 370 },
  },
  {
    id: 'animal_pack_redux_bear',
    name: 'Bear',
    description: 'Animal Pack Redux - bear',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_bear.png',
    thumbnail: '/assets/enemies/animal_pack_redux_bear.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 154, height: 132 },
  },
  {
    id: 'animal_pack_redux_buffalo',
    name: 'Buffalo',
    description: 'Animal Pack Redux - buffalo',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_buffalo.png',
    thumbnail: '/assets/enemies/animal_pack_redux_buffalo.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 183, height: 152 },
  },
  {
    id: 'animal_pack_redux_chick',
    name: 'Chick',
    description: 'Animal Pack Redux - chick',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_chick.png',
    thumbnail: '/assets/enemies/animal_pack_redux_chick.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 129, height: 128 },
  },
  {
    id: 'animal_pack_redux_chicken',
    name: 'Chicken',
    description: 'Animal Pack Redux - chicken',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_chicken.png',
    thumbnail: '/assets/enemies/animal_pack_redux_chicken.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 128, height: 145 },
  },
  {
    id: 'animal_pack_redux_cow',
    name: 'Cow',
    description: 'Animal Pack Redux - cow',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_cow.png',
    thumbnail: '/assets/enemies/animal_pack_redux_cow.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 145, height: 128 },
  },
  {
    id: 'animal_pack_redux_crocodile',
    name: 'Crocodile',
    description: 'Animal Pack Redux - crocodile',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_crocodile.png',
    thumbnail: '/assets/enemies/animal_pack_redux_crocodile.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 129, height: 128 },
  },
  {
    id: 'animal_pack_redux_dog',
    name: 'Dog',
    description: 'Animal Pack Redux - dog',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_dog.png',
    thumbnail: '/assets/enemies/animal_pack_redux_dog.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 129, height: 157 },
  },
  {
    id: 'animal_pack_redux_duck',
    name: 'Duck',
    description: 'Animal Pack Redux - duck',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_duck.png',
    thumbnail: '/assets/enemies/animal_pack_redux_duck.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 129, height: 128 },
  },
  {
    id: 'animal_pack_redux_elephant',
    name: 'Elephant',
    description: 'Animal Pack Redux - elephant',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_elephant.png',
    thumbnail: '/assets/enemies/animal_pack_redux_elephant.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 183, height: 154 },
  },
  {
    id: 'animal_pack_redux_frog',
    name: 'Frog',
    description: 'Animal Pack Redux - frog',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_frog.png',
    thumbnail: '/assets/enemies/animal_pack_redux_frog.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 130, height: 144 },
  },
  {
    id: 'animal_pack_redux_giraffe',
    name: 'Giraffe',
    description: 'Animal Pack Redux - giraffe',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_giraffe.png',
    thumbnail: '/assets/enemies/animal_pack_redux_giraffe.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 154, height: 162 },
  },
  {
    id: 'animal_pack_redux_goat',
    name: 'Goat',
    description: 'Animal Pack Redux - goat',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_goat.png',
    thumbnail: '/assets/enemies/animal_pack_redux_goat.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 184, height: 171 },
  },
  {
    id: 'animal_pack_redux_gorilla',
    name: 'Gorilla',
    description: 'Animal Pack Redux - gorilla',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_gorilla.png',
    thumbnail: '/assets/enemies/animal_pack_redux_gorilla.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 129, height: 128 },
  },
  {
    id: 'animal_pack_redux_hippo',
    name: 'Hippo',
    description: 'Animal Pack Redux - hippo',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_hippo.png',
    thumbnail: '/assets/enemies/animal_pack_redux_hippo.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 154, height: 128 },
  },
  {
    id: 'animal_pack_redux_horse',
    name: 'Horse',
    description: 'Animal Pack Redux - horse',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_horse.png',
    thumbnail: '/assets/enemies/animal_pack_redux_horse.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 129, height: 141 },
  },
  {
    id: 'animal_pack_redux_monkey',
    name: 'Monkey',
    description: 'Animal Pack Redux - monkey',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_monkey.png',
    thumbnail: '/assets/enemies/animal_pack_redux_monkey.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 174, height: 128 },
  },
  {
    id: 'animal_pack_redux_moose',
    name: 'Moose',
    description: 'Animal Pack Redux - moose',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_moose.png',
    thumbnail: '/assets/enemies/animal_pack_redux_moose.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 269, height: 162 },
  },
  {
    id: 'animal_pack_redux_narwhal',
    name: 'Narwhal',
    description: 'Animal Pack Redux - narwhal',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_narwhal.png',
    thumbnail: '/assets/enemies/animal_pack_redux_narwhal.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 138, height: 155 },
  },
  {
    id: 'animal_pack_redux_owl',
    name: 'Owl',
    description: 'Animal Pack Redux - owl',
    type: 'sprite',
    category: 'enemies',
    path: '/assets/enemies/animal_pack_redux_owl.png',
    thumbnail: '/assets/enemies/animal_pack_redux_owl.png',
    tags: ['enemies', 'animal_pack_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Animal Pack Redux pack',
    size: { width: 128, height: 128 },
  },
  {
    id: 'background_elements_castle_beige',
    name: 'Castle Beige',
    description: 'Background Elements - castle_beige',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_castle_beige.png',
    thumbnail: '/assets/backgrounds/background_elements_castle_beige.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 204, height: 182 },
  },
  {
    id: 'background_elements_castle_grey',
    name: 'Castle Grey',
    description: 'Background Elements - castle_grey',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_castle_grey.png',
    thumbnail: '/assets/backgrounds/background_elements_castle_grey.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 204, height: 182 },
  },
  {
    id: 'background_elements_castle_wall',
    name: 'Castle Wall',
    description: 'Background Elements - castle_wall',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_castle_wall.png',
    thumbnail: '/assets/backgrounds/background_elements_castle_wall.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 295, height: 138 },
  },
  {
    id: 'background_elements_cloud1',
    name: 'Cloud1',
    description: 'Background Elements - cloud1',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud1.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud1.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 190, height: 127 },
  },
  {
    id: 'background_elements_cloud2',
    name: 'Cloud2',
    description: 'Background Elements - cloud2',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud2.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud2.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 200, height: 125 },
  },
  {
    id: 'background_elements_cloud3',
    name: 'Cloud3',
    description: 'Background Elements - cloud3',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud3.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud3.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 177, height: 121 },
  },
  {
    id: 'background_elements_cloud4',
    name: 'Cloud4',
    description: 'Background Elements - cloud4',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud4.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud4.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 228, height: 124 },
  },
  {
    id: 'background_elements_cloud5',
    name: 'Cloud5',
    description: 'Background Elements - cloud5',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud5.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud5.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 238, height: 135 },
  },
  {
    id: 'background_elements_cloud6',
    name: 'Cloud6',
    description: 'Background Elements - cloud6',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud6.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud6.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 266, height: 138 },
  },
  {
    id: 'background_elements_cloud7',
    name: 'Cloud7',
    description: 'Background Elements - cloud7',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud7.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud7.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 234, height: 118 },
  },
  {
    id: 'background_elements_cloud8',
    name: 'Cloud8',
    description: 'Background Elements - cloud8',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud8.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud8.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 210, height: 119 },
  },
  {
    id: 'background_elements_cloud9',
    name: 'Cloud9',
    description: 'Background Elements - cloud9',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_cloud9.png',
    thumbnail: '/assets/backgrounds/background_elements_cloud9.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 213, height: 119 },
  },
  {
    id: 'background_elements_fence',
    name: 'Fence',
    description: 'Background Elements - fence',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_fence.png',
    thumbnail: '/assets/backgrounds/background_elements_fence.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 128, height: 88 },
  },
  {
    id: 'background_elements_fence_piece',
    name: 'Fence Piece',
    description: 'Background Elements - fence_piece',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_fence_piece.png',
    thumbnail: '/assets/backgrounds/background_elements_fence_piece.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 110, height: 86 },
  },
  {
    id: 'background_elements_grass1',
    name: 'Grass1',
    description: 'Background Elements - grass1',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_grass1.png',
    thumbnail: '/assets/backgrounds/background_elements_grass1.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 26, height: 29 },
  },
  {
    id: 'background_elements_grass2',
    name: 'Grass2',
    description: 'Background Elements - grass2',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_grass2.png',
    thumbnail: '/assets/backgrounds/background_elements_grass2.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 26, height: 29 },
  },
  {
    id: 'background_elements_grass3',
    name: 'Grass3',
    description: 'Background Elements - grass3',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_grass3.png',
    thumbnail: '/assets/backgrounds/background_elements_grass3.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 38, height: 35 },
  },
  {
    id: 'background_elements_grass4',
    name: 'Grass4',
    description: 'Background Elements - grass4',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_grass4.png',
    thumbnail: '/assets/backgrounds/background_elements_grass4.png',
    tags: ['backgrounds', 'background_elements'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements pack',
    size: { width: 38, height: 35 },
  },
  {
    id: 'background_elements_redux_mountainA',
    name: 'Mountaina',
    description: 'Background Elements Redux - mountainA',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_mountainA.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_mountainA.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements Redux pack',
    size: { width: 356, height: 352 },
  },
  {
    id: 'background_elements_redux_mountainB',
    name: 'Mountainb',
    description: 'Background Elements Redux - mountainB',
    type: 'sprite',
    category: 'backgrounds',
    path: '/assets/backgrounds/background_elements_redux_mountainB.png',
    thumbnail: '/assets/backgrounds/background_elements_redux_mountainB.png',
    tags: ['backgrounds', 'background_elements_redux'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Background Elements Redux pack',
    size: { width: 340, height: 278 },
  },
  {
    id: 'block_pack_box',
    name: 'Box',
    description: 'Block Pack - box',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_box.png',
    thumbnail: '/assets/tiles/block_pack_box.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_box_treasure',
    name: 'Box Treasure',
    description: 'Block Pack - box_treasure',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_box_treasure.png',
    thumbnail: '/assets/tiles/block_pack_box_treasure.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_box_wide',
    name: 'Box Wide',
    description: 'Block Pack - box_wide',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_box_wide.png',
    thumbnail: '/assets/tiles/block_pack_box_wide.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_cart',
    name: 'Cart',
    description: 'Block Pack - cart',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_cart.png',
    thumbnail: '/assets/tiles/block_pack_cart.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_cart_horse',
    name: 'Cart Horse',
    description: 'Block Pack - cart_horse',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_cart_horse.png',
    thumbnail: '/assets/tiles/block_pack_cart_horse.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_cart_top',
    name: 'Cart Top',
    description: 'Block Pack - cart_top',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_cart_top.png',
    thumbnail: '/assets/tiles/block_pack_cart_top.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_character_horse',
    name: 'Character Horse',
    description: 'Block Pack - character_horse',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_character_horse.png',
    thumbnail: '/assets/tiles/block_pack_character_horse.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_character_man',
    name: 'Character Man',
    description: 'Block Pack - character_man',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_character_man.png',
    thumbnail: '/assets/tiles/block_pack_character_man.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_character_wizard',
    name: 'Character Wizard',
    description: 'Block Pack - character_wizard',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_character_wizard.png',
    thumbnail: '/assets/tiles/block_pack_character_wizard.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_character_woman',
    name: 'Character Woman',
    description: 'Block Pack - character_woman',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_character_woman.png',
    thumbnail: '/assets/tiles/block_pack_character_woman.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_mud',
    name: 'Detail Mud',
    description: 'Block Pack - detail_mud',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_mud.png',
    thumbnail: '/assets/tiles/block_pack_detail_mud.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_snow',
    name: 'Detail Snow',
    description: 'Block Pack - detail_snow',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_snow.png',
    thumbnail: '/assets/tiles/block_pack_detail_snow.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_window',
    name: 'Detail Window',
    description: 'Block Pack - detail_window',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_window.png',
    thumbnail: '/assets/tiles/block_pack_detail_window.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_windowBlue',
    name: 'Detail Windowblue',
    description: 'Block Pack - detail_windowBlue',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_windowBlue.png',
    thumbnail: '/assets/tiles/block_pack_detail_windowBlue.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_windowCastle',
    name: 'Detail Windowcastle',
    description: 'Block Pack - detail_windowCastle',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_windowCastle.png',
    thumbnail: '/assets/tiles/block_pack_detail_windowCastle.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_windowRed',
    name: 'Detail Windowred',
    description: 'Block Pack - detail_windowRed',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_windowRed.png',
    thumbnail: '/assets/tiles/block_pack_detail_windowRed.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_detail_windowSlit',
    name: 'Detail Windowslit',
    description: 'Block Pack - detail_windowSlit',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_detail_windowSlit.png',
    thumbnail: '/assets/tiles/block_pack_detail_windowSlit.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
  {
    id: 'block_pack_door',
    name: 'Door',
    description: 'Block Pack - door',
    type: 'sprite',
    category: 'tiles',
    path: '/assets/tiles/block_pack_door.png',
    thumbnail: '/assets/tiles/block_pack_door.png',
    tags: ['tiles', 'block_pack'],
    license: 'CC0 - Kenney.nl',
    suggestedUse: 'From Block Pack pack',
    size: { width: 64, height: 100 },
  },
];
